### ISSUE TITLE
Local Error: Record Overflow

### ISSUE THREAD

**Issue by jheinz1999** [unixpickle/kahoot-hack#10]
A friend and I have been trying to get this code to work for awhile now. Every time we run any of the tools, we receive this error: "Error: Local error: Record overflow."

**Comment by unixpickle** [comment]
It is very possible that my code is broken. I wrote this a long time ago. If Kahoot changed their protocol since then, my code almost definitely won't work. I do not plan on fixing this, ever, because I have no reason to and the only people who come to this repository are script kiddies.

**Comment by jheinz1999** [comment]
That makes sense. Still, I've been looking all over the place for an answer to this. Would you happen to know what a record overflow error is? I haven't been able to locate any significant documentation on it.

**Comment by unixpickle** [comment]
What operating system were you using when you got this error. I tested the code just now on OS X and Linux and it worked on both.

**Comment by sciaschi1** [comment]
It seems like its an issue with the length of the decryption when its connecting. Its returning a value greater than the max its supposed to allow.

As per tls:
"No valid TLS record has a type of 0x80, however SSLv2 handshakes start with a uint16 length where the MSB is set and the first record is always < 256 bytes long. Therefore typ == 0x80 strongly suggests an SSLv2 client."

**Comment by msemple1111** [comment]
@unixpickle I think this is just a different error related to bug #9. Perhaps after #9 is fixed come back to this and try to reproduce the error.

P.S. @jheinz1999  - If want to use a basic version of these tools without this error, use my python version [github.com/msemple1111/kahoot-hack](https://github.com/msemple1111/kahoot-hack). It is more basic than these tools but can be quite fun.
