### ISSUE TITLE
Stop It?

### ISSUE THREAD

**Issue by Zorphix** [unixpickle/kahoot-hack#100]
How to stop these processes on Termux Android?

**Comment by unixpickle** [comment]
ping @Noxturnix

**Comment by Zorphix** [comment]
would this remove the bots from the game?

**Comment by unixpickle** [comment]
Since @Noxturnix is the one who implemented the Android version, he is likely to have an answer. I've never personally used the Android version.

**Comment by Zorphix** [comment]
ok thank you

**Comment by Noxturnix** [comment]
You can terminate the process by pressing CTRL+C like you are using this program on PC. [Hacker's Keyboard](https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard) can help you to do that on Android device.

Sorry, high latency.
