### ISSUE TITLE
failed to connect:

### ISSUE THREAD

**Issue by githubpages** [unixpickle/kahoot-hack#102]
failed to create session: failed to defeat challenge: decode.call(this, 'VsSxlDuKvmpXPxuhJyL5YhyPOpive8Z3jDYhqGe8FxIBKJqvsfLYNq7v25JvAZXNMn5YvgCidGX4YzxTbc33oe6xlYsZdGFO7L2N'); function decode(message) {var offset = (88 * 67 + (19 * (85 + 5))); if (this.angular.isDate(offset)) {console.log("Offset derived as: {", offset, "}");}return _.replace(message, /./g, function(char, position) {return String.fromCharCode((((char.charCodeAt(0) * position) + offset) % 77) + 48);});}

**Comment by nowell7** [comment]
mute

**Comment by unixpickle** [comment]
Should be fixed with the new safeval.pw. The fix is temporary.
