### ISSUE TITLE
Failed to create session

### ISSUE THREAD

**Issue by ChaosZerg** [unixpickle/kahoot-hack#103]
No matter which script i want to run i get this error:

failed to connect: failed to create session: failed to defeat challenge: decode.call(this, 'HZMpDTWE6DOGXyeiM0MTGCmN9Rjp8YgeFpxNpx2pHJJInQ4eIyM4KkwsFYdYx867wEji6eAlPybQ6NVIayeClmqJMYZM8TTVCT7O'); function decode(message) {var offset = (6 + (58 + 98)) + 44 * 13; if (this.angular.isObject(offset)) {console.log("Offset derived as: {", offset, "}");}return _.replace(message, /./g, function(char, position) {return String.fromCharCode((((char.charCodeAt(0) * position) + offset) % 77) + 48);});}
exit status 1

**Comment by reteps** [comment]
Same error

**Comment by unixpickle** [comment]
Should be fixed with the new safeval.pw. Not sure how long it will continue working...
