### ISSUE TITLE
Please help UnixPickle *I'm in distress*

### ISSUE THREAD

**Issue by DeathlyCynical** [unixpickle/kahoot-hack#104]
Hello! I just want you to know I absolutely love your program. I've been using it on Android for over a month, but recently, it just told me unable to connect: failed to create session, then has a bunch of random code over it. (Check the other issue threads) I really want to continue using this program, but I can't without your godly help! Thank you so much in advance, and know that we love you for what you do 👍 :) 

Thanks!!! 
Hope it gets fixed fast, have a great day!

**Comment by theukbeast089** [comment]
Same

**Comment by unixpickle** [comment]
Should be fixed with the new safeval.pw. The fix is temporary.
