### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by theukbeast089** [unixpickle/kahoot-hack#105]

**Comment by theukbeast089** [comment]
go run kahoot/rand.go 584435 " bernie " 133
failed to connect: failed to create session: failed to defeat challenge: decode.call(this, 'FnAOj4jW1lGNxKuzJvx1vjBFivGGnCeRCvBGpxo6j1rqWnxDpkuArfFVKtACDtA14Wie8a6OnSg3WHJphJezE8sDhKt0m1ihca4R'); function decode(message) {var offset = (73 + 82 + (29 * 35)); if (this.angular.isObject(offset)) {console.log("Offset derived as: {", offset, "}");}return _.replace(message, /./g, function(char, position) {return String.fromCharCode((((char.charCodeAt(0) * position) + offset) % 77) + 48);});}
exit status 1

**Comment by unixpickle** [comment]
Should be fixed with the new safeval.pw. The fix is temporary.
