### ISSUE TITLE
site section - website?

### ISSUE THREAD

**Issue by reteps** [unixpickle/kahoot-hack#106]
Does the site have a website?

**Comment by unixpickle** [comment]
There used to be a website for kahoot-hack, but it got too popular and I took it down.

**Comment by reteps** [comment]
would it spam the answers? Or just play normally. Also, can `kahoot-play` play over port 443?

**Comment by unixpickle** [comment]
I believe the site was equivalent to kahoot-flood.

I'm fairly certain that kahoot-play uses HTTPS (or WSS to be specific).

**Comment by reteps** [comment]
ok, thanks. I will send a PR with `kahoot-auto` (answers correctly) soon.
