### ISSUE TITLE
How would I use this?

### ISSUE THREAD

**Issue by gavintheplague** [unixpickle/kahoot-hack#11]
I already googled it, literally found nothing. Would I use tampermonkey? but this isnt user.js? or is it? just really confused...

**Comment by msemple1111** [comment]
Make sure the go Lang is installed on your command line. Use the commands in the instructions.
It will prompt you the rest of the instructions.
It probably doesn't work anymore anyway.

**Comment by unixpickle** [comment]
I added more instructions to the [README](https://github.com/unixpickle/kahoot-hack/blob/master/README.md). This should help, for now.
