### ISSUE TITLE
kahoot-auto issues

### ISSUE THREAD

**Issue by reteps** [unixpickle/kahoot-hack#110]
running `kahoot-auto` with `go run main.go` gives me:

```
./main.go:17: undefined: kahoot.QuizInfo
./main.go:65: undefined: kahoot.AccessToken
./main.go:69: undefined: kahoot.QuizInformation
```

Maybe it's not finding `info.go` somehow?

**Comment by unixpickle** [comment]
As far as I can tell, this error doesn't make any sense. Make sure your GOPATH is correct and that the latest version of kahoot-hack is in the GOPATH.
