### ISSUE TITLE
Kahoot-rand issue

### ISSUE THREAD

**Issue by tedgp908** [unixpickle/kahoot-hack#112]
The bots enter the Kahoot game normally, but when it comes to answering questions the teachers display does not show them answering, but the output of the Kahoot Hack program says it is. Once the teacher goes to the scoreboard the bots are shown receiving points.

**Comment by unixpickle** [comment]
This sounds more like a bug on Kahoot's end than on ours. I'll leave this open incase anybody else wants to investigate.

**Comment by unixpickle** [comment]
Should be fixed by #140
