### ISSUE TITLE
Rand fails to defeat challenge

### ISSUE THREAD

**Issue by fishfishfish2104** [unixpickle/kahoot-hack#114]
Rand fails with this error code 
`failed to connect: failed to create session: failed to defeat chalnge: decode.call(this, 'Zf2vtB8iUMv0iokKHm3eUQgEEIvxQ0Yyu2ZSjbdqHLzr1igKkVQDW0vKeP7Xq5Ylmx5KqCjRFC4nrdpuLXENzZwFOCRLZrwdPb2k'); function decode(message) {var offset = (11 * 68 + (54 * 52)) + 57 + 21; if (this.angular.isArray(offset)) {console.log("Offset derived as: {", offset, "}");}return _.replace(message, /./g, function(char, position) {return String.fromCharCode((((char.charCodeAt(0) * position) + offset) % 77) + 48);});}
exit status 1`

**Comment by unixpickle** [comment]
Thanks for letting me know. There was a problem with the server for `safeval.pw`. If this happens again, let me know.

**Comment by unixpickle** [comment]
Figured out the source of the bug. Should be fixed longer-term now.
