### ISSUE TITLE
Failed to connect, failed to create session, failed to defeat challenge...

### ISSUE THREAD

**Issue by elisaado** [unixpickle/kahoot-hack#121]
When I start kahoot-rand:
`go run kahoot-hack/kahoot-rand/main.go <code> "x" 5`
```Entered with 5 bots.
Terminate this program to stop the automatons...
failed to connect: failed to create session: failed to defeat challenge: decode.call(this, 'bYz31iSGfMnUI2kjFaeOAeaDpdu5LswsERumLvqlQxvRwbnmjqcURHdp5lCuHBGoPMNXXMlY4e4o68yySIyS1BEoBE23z5EtqFFy'); function decode(message) {var offset = 22 + 94 * (93 * 38) * (93 * 95 * 47); if (this.angular.isString(offset)) {console.log("Offset derived as: {", offset, "}");}return _.replace(message, /./g, function(char, position) {return String.fromCharCode((((char.charCodeAt(0) * position) + offset) % 77) + 48);});}
exit status 1
```
Looks like kahoot implemented some anti bot thing?

Go version:
`go version`
```go version go1.9 linux/amd64```

**Comment by rushilsrivastava** [comment]
Same issue here.

**Comment by unixpickle** [comment]
Try again. This tool depends on a web server to decipher kahoot's challenge strings, and that server goes down from time to time.

**Comment by shadowbrony33** [comment]
@unixpickle why not let the user run the deciphering tools?

**Comment by elisaado** [comment]
@unixpickle Now it works. What @shadowbrony33 suggested is a pretty good idea.

I have experienced another issue with kahoot-rand though... I'll open a new issue for that.


* closed *
