### ISSUE TITLE
Extra function??

### ISSUE THREAD

**Issue by connerdassen** [unixpickle/kahoot-hack#124]
When I'm on mobile, and I type dir in the kahoot directory there are 8 files instead of 7. There are the ones listed: flood, play, rand, crash, html, profane and xss. But theres another one named auto. I thought it let you choose what type to use, but I can't figure it out. It also has weird parameters, like email. Could someone please explain what it is with an example?

**Comment by shadowbrony33** [comment]
It creates a bot that can answer all the quiz questions correctly if it is setup right.

**Comment by connerdassen** [comment]
@shadowbrony33 What is meant by quizid, and what is the account that you log in with?

**Comment by connerdassen** [comment]
@shadowbrony33 I'm getting the error panic: runtime error: index out of range

**Comment by shadowbrony33** [comment]
The account is the https://create.kahoot.com account

**Comment by shadowbrony33** [comment]
The quiz id would be like this: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

https://create.kahoot.it/#quiz/e9abda7d-aa86-XXXX-bb72-44XXXX46037a
                                             ^                    This part of the URL                ^

**Comment by connerdassen** [comment]
@shadowbrony33ok thank you

**Comment by connerdassen** [comment]
@shadowbrony33 Do you need the account of the host? Because it's pointless then I don't know my teachers account

**Comment by shadowbrony33** [comment]
No, you can use any account.

>"Teacher's account"
>Spamming bots during class

F*cking script kiddies...

**Comment by connerdassen** [comment]
@shadowbrony33 Seems like I do need the hosts account, when using another account I'm getting an error

**Comment by shadowbrony33** [comment]
@connerdassen What is the error you are getting?

**Comment by connerdassen** [comment]
@shadowbrony33
panic: runtime error: index out of range
                                                        goroutine 1 [running]:
main.main()                                                     /data/data/com.termux/files/home/kahoot/auto.go:110 +0x7cc                                              exit status 2

**Comment by shadowbrony33** [comment]
@connerdassen 
![image](https://user-images.githubusercontent.com/14355117/32056361-b1acd28c-ba21-11e7-829e-2b106970d193.png)

I'm running on a quizID that is tied to another account, you are probably encountering another issue or entered in something incorrectly.

**Comment by shadowbrony33** [comment]
@unixpickle Please close this pointless issue.

**Comment by connerdassen** [comment]
@shadowbrony33 I can connect, the error happens when a question starts

**Comment by shadowbrony33** [comment]
@connerdassen you're problem is occurring in here: 
`else if action.Type == kahoot.QuestionAnswers {
			answer, _ := strconv.Atoi(answers[questionnum][2])
			if err := quiz.Send(answer); err != nil {
				fmt.Fprintln(os.Stderr, "Could not answer:", err)
				os.Exit(1)
			}'

This has nothing to do with your kahoot account

**Comment by connerdassen** [comment]
@shadowbrony33 I'm pretty sure you need the hosts account, when I used another account with the matching quizID it answers wrong, and it answers the correct answers from a kahoot on that account

**Comment by shadowbrony33** [comment]
Strange, I'm not encountering this issue, do note that sometimes there is a delay between the question and when the not responds. Also make sure the quiz you are using matches the quzid you enter in. If you are still having this issue then you can easily duplicate the quiz you want to use.

**Comment by connerdassen** [comment]
@shadowbrony33 I may have been a bit unclear, I want to know wether it is possible to use on someone elses kahoot. Is this possible?

**Comment by shadowbrony33** [comment]
Someone else's quiz? Yes. You can use other peoples' quizzes without their account as long as it is public.

**Comment by connerdassen** [comment]
@shadowbrony33 Thank you, I didn't know it had to be public. It's working now
