### ISSUE TITLE
KAHOOT RAND ISSUE

### ISSUE THREAD

**Issue by r1161177** [unixpickle/kahoot-hack#128]
I see that several issues regarding Kahoot rand have been submitted, but I see no solution (yet). Is this due to new Kahoot restrictions/security/changes? If so, are you able to update your codes accordingly?

Everything works fine: bots join Kahoot games just fine, but when it comes to answering the questions, nothing happens, even though the output in the CMD on Windows says otherwise.

This is the only functional Kahoot "hack" available, a lot of people, including myself, enjoy using it. Thank you for all the efforts you have put into this project. I hope you will continue maintaining it.

**Comment by shadowbrony33** [comment]
@r1161177 The bots' responses still register (if you look at their scores), however their responses don't showup for some reason.

**Comment by r1161177** [comment]
Exactly, @Shadowbrony33. The problem is that the bots do not actually answer any questions.

**Comment by shadowbrony33** [comment]
I know that their answers don't show up but they still get a score when I use it. You'll have to ask @unixpickle why that is.

**Comment by elisaado** [comment]
Same here.

**Comment by r1161177** [comment]
No news?

**Comment by elisaado** [comment]
Even when they join during the question, they still don't answer (/ we don't see the answer)

**Comment by connerdassen** [comment]
Is it really necessary for the answers to show up during the question? They
still get the scores so they will show up in the leaderboard.

**Comment by elisaado** [comment]
@connerdassen that's one of the fun things about it! (I've heard a ton of stories from friends about the teacher being stunned and stuff)

**Comment by r1161177** [comment]
Exactly, @elisaado! The most funny part of it is to see the answers increasing rapidly, the sound of the speed and the lag. Please bring back this awesome feature, @unixpickle!

**Comment by unixpickle** [comment]
This should be fixed by #140

**Comment by elisaado** [comment]
Thank you @unixpickle. Will test
