### ISSUE TITLE
how to use kahoot-rand

### ISSUE THREAD

**Issue by fishfishfish2104** [unixpickle/kahoot-hack#13]
when i try to use kahoot-rand this happens 
go run main.go 110149 hi 1000
Terminate this program to stop the automatons...
failed to connect: read tcp 54.253.141.15:443: connection reset by peer
exit status 1

this is with a real pin

**Comment by unixpickle** [comment]
I'd say try using a smaller number. Some--most--OSes don't like a ton of
simultaneous network connections. Let me know if it works for something
like 50...

**Comment by fishfishfish2104** [comment]
ok it worked now thanks
