### ISSUE TITLE
can't run any files

### ISSUE THREAD

**Issue by 1000goalgaming** [unixpickle/kahoot-hack#130]
C:\27\kahoot-hack-master\kahoot-hack-master\kahoot-rand>go run main.go
main.go:17:2: cannot find package "github.com/unixpickle/kahoot-hack/kahoot" in any of:
        C:\Go\src\github.com\unixpickle\kahoot-hack\kahoot (from $GOROOT)
        C:\27\src\github.com\unixpickle\kahoot-hack\kahoot (from $GOPATH)

**Comment by unixpickle** [comment]
You didn't use `go get` to download the package like you should have.
