### ISSUE TITLE
Ubuntu 14.04 VPS Problem

### ISSUE THREAD

**Issue by MambaAgar** [unixpickle/kahoot-hack#133]
Ive been going trying to fiqure this out forever and then i thought well wow iI think I should ask the developer i go tthis problem when doing go run main.go
 go run main.go
main.go:13:2: cannot find package "github.com/unixpickle/kahoot-hack/kahoot" in any of:
        /usr/local/go/src/github.com/unixpickle/kahoot-hack/kahoot (from $GOROOT)
        /home/cabox/workspace/src/github.com/unixpickle/kahoot-hack/kahoot (from $GOPATH)

**Comment by shadowbrony33** [comment]
use `go get` NOT `git clone` to clone the repository and dependancies

**Comment by Messier-16** [comment]
Same issue exists for me as well, never used git clone

**Comment by chipandsalsa** [comment]
how do you fix it i have the same issues to

**Comment by Noxturnix** [comment]
You need to set your GOPATH first. Use `export GOPATH=/path/to/your/workspace` to set your GOPATH. (In this case use `export GOPATH=/home/cabox/workspace` to solve the problem)
