### ISSUE TITLE
Kahoot Rand no longer working

### ISSUE THREAD

**Issue by a-lindsay** [unixpickle/kahoot-hack#135]
Title says it all, when I got to use Kahoot-Rand on a kahoot they bots never connect and the console window closes.

**Comment by ACPixel** [comment]
indeed it doenst, makes me sad

**Comment by unixpickle** [comment]
I tried it just now, and it worked for me. Can you check if it is still broken for you?

**Comment by a-lindsay** [comment]
It's fixed! Thanks1
