### ISSUE TITLE
How to configure site?

### ISSUE THREAD

**Issue by SimplyPancake** [unixpickle/kahoot-hack#136]
Hi, I am running the site on my apache2 server. I put the site in the following directory:
`/webtools/kahoot-flood/assets/index.html`

When i click on flood(in the index.html), it sends me to the following directory:
`/hack`

But that doesn't exist! I tried editing some code, but it didn't work. What can i do?

**Comment by GodlyEcstasy** [comment]
its way easier than that. just use `go run main.go (port)` then go to serverIP:port to view the page. it only spams 20 bots but that can be easily changed

**Comment by unixpickle** [comment]
@GodlyEcstasy is right. You do not need to run this under apache. It is its own web server.
