### ISSUE TITLE
Man someone tell how to do this on android please

### ISSUE THREAD

**Issue by Senya247** [unixpickle/kahoot-hack#176]
i've typed and everything the dude said in termux and have given termux storage access.
Now what do i do? How do i run it?
Please mates help im kinda new to this stuff

**Comment by Nightmare247** [comment]
update-
i ran
`go run ~/kahoot/<hack>.go`

and it told me the parameters
then i ran-
`go run crash.go <MyGamePinHere> <MyNameHere>`
it ran successfully
but it raised the exception-
failed to connect: failed to create session: failed to defeat challenge: decode.call(this, 'GThTMLelxS9QYKKf0Q5LwlncqSqQwbRGNLRSdvm5MFiP1YHEDDPs9Vv3uDyz6DDc7ZJcw3AMBKzf46JKuCYKQLw2ITf4AWjLS2aV'); function decode(message) {var offset = (7    *       50) + (70 + 86) + (15 + (7     *        24)); if(       this    .       angular   . isObject   ( offset   )) console    . log ("Offset derived as: {", offset, "}"); return     _       .       replace         ( message,/./g, function(char, position) {return
