### ISSUE TITLE
main.go:13:2: invalid import path: "https://github.com/unixpickle/kahoot-hack/tree/master/kahoot"

### ISSUE THREAD

**Issue by Jesper117** [unixpickle/kahoot-hack#178]
When I execute **go run main.go** this error occurs.

**Comment by Jesper117** [comment]
im dumb sorry

**Comment by carterlasalle** [comment]
> im dumb sorry

how did you fix?

**Comment by mamamia5x** [comment]
@RocketNinja15 use github.com/unixpickle/kahoot-hack/tree/master/kahoot
