### ISSUE TITLE
help running this

### ISSUE THREAD

**Issue by joondepoon** [unixpickle/kahoot-hack#18]
Whenever I try to run this it waits a while and then returns this:
`Usage: flood <game pin> <nickname prefix> <count>`
exit status 1
 I don't know what I did wrong, I entered this in my cmd:
`go run main.go flood 791373 deinemutter 100`
What am I doing wrong?

**Comment by unixpickle** [comment]
You do not need to put "flood" as an argument. Simply doing `go run main.go 791373 deinemutter 100` should work.

**Comment by joondepoon** [comment]
oh, oops

**Comment by joondepoon** [comment]
when I do that, it returns this:

`Terminate this program to stop the automatons...
failed to connect: read tcp 10.160.230.76:51776->54.217.54.76:443: wsarecv: An existing connection was forcibly closed by the remote host.
exit status 1`

**Comment by joondepoon** [comment]
nevermind it's working

**Comment by MatSn0w** [comment]
I had the same problem before, but I got it now:

First, make sure to know where you put the `kahoot-hack` folder (and `kahoot-flood`). In my case, it was:
`C:\Go\src\github.com\unixpickle\`

So I entered the following command to CMD:
`go run c:/go/src/github.com/unixpickle/kahoot-hack/kahoot-flood/main.go 123456 hacker 999`

And that works!

Happy Hacking!
