### ISSUE TITLE
Problem with Executing the Scripts (Ubuntu 14.04)

### ISSUE THREAD

**Issue by ItsLolPhp** [unixpickle/kahoot-hack#20]
This is from my terminal in Ubuntu
I have the Go Programming Language installed
and I installed the Dependencies
But having Trouble with the $GOPATH
Mind helping?
___

> lolphp@pc:~$ mkdir gocode
lolphp@pc:~$ export GOPATH=$HOME/gocode
lolphp@pc:~$ cd gocode
lolphp@pc:~/gocode$ mkdir -p src/github.com/unixpickle
lolphp@pc:~/gocode$ cd src/github.com/unixpickle
lolphp@pc:~/gocode/src/github.com/unixpickle$ mkdir flood
lolphp@pc:~/gocode/src/github.com/unixpickle$ cd flood
lolphp@pc:~/gocode/src/github.com/unixpickle/flood$ vim flood.go
The program 'vim' can be found in the following packages:
 * vim
 * vim-gnome
 * vim-tiny
 * vim-athena
 * vim-gtk
 * vim-nox
Try: sudo apt-get install <selected package>
lolphp@pc:~/gocode/src/github.com/unixpickle/flood$ sudo apt-get install vim
[sudo] password for lolphp: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  vim-runtime
Suggested packages:
  ctags vim-doc vim-scripts
The following NEW packages will be installed:
  vim vim-runtime
0 upgraded, 2 newly installed, 0 to remove and 7 not upgraded.
Need to get 5,844 kB of archives.
After this operation, 28.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty/main vim-runtime all 2:7.4.052-1ubuntu3 [4,888 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu/ trusty/main vim amd64 2:7.4.052-1ubuntu3 [956 kB]
Fetched 5,844 kB in 8s (659 kB/s)                                              
Selecting previously unselected package vim-runtime.
(Reading database ... 198016 files and directories currently installed.)
Preparing to unpack .../vim-runtime_2%3a7.4.052-1ubuntu3_all.deb ...
Adding 'diversion of /usr/share/vim/vim74/doc/help.txt to /usr/share/vim/vim74/doc/help.txt.vim-tiny by vim-runtime'
Adding 'diversion of /usr/share/vim/vim74/doc/tags to /usr/share/vim/vim74/doc/tags.vim-tiny by vim-runtime'
Unpacking vim-runtime (2:7.4.052-1ubuntu3) ...
Selecting previously unselected package vim.
Preparing to unpack .../vim_2%3a7.4.052-1ubuntu3_amd64.deb ...
Unpacking vim (2:7.4.052-1ubuntu3) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up vim-runtime (2:7.4.052-1ubuntu3) ...
Processing /usr/share/vim/addons/doc
Setting up vim (2:7.4.052-1ubuntu3) ...
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vim (vim) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vimdiff (vimdiff) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rvim (rvim) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rview (rview) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vi (vi) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/view (view) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/ex (ex) in auto mode
lolphp@pc:~/gocode/src/github.com/unixpickle/flood$ vim flood.go
lolphp@pc:~/gocode/src/github.com/unixpickle/flood$ go install
flood.go:10:2: cannot find package "github.com/unixpickle/kahoot-hack/kahoot" in any of:
	/usr/src/pkg/github.com/unixpickle/kahoot-hack/kahoot (from $GOROOT)
	/home/lolphp/gocode/src/github.com/unixpickle/kahoot-hack/kahoot (from $GOPATH)
lolphp@pc:~/gocode/src/github.com/unixpickle/flood$ ls ~/gocode/bin/flood
ls: cannot access /home/lolphp/gocode/bin/flood: No such file or directory
lolphp@pc:~/gocode/src/github.com/unixpickle/flood$ clear

lolphp@pc:~/gocode/src/github.com/unixpickle/flood$ ls
flood.go
lolphp@pc:~/gocode/src/github.com/unixpickle/flood$ go run flood.go
flood.go:10:2: cannot find package "github.com/unixpickle/kahoot-hack/kahoot" in any of:
	/usr/src/pkg/github.com/unixpickle/kahoot-hack/kahoot (from $GOROOT)
	/home/lolphp/gocode/src/github.com/unixpickle/kahoot-hack/kahoot (from $GOPATH)
lolphp@pc:~/gocode/src/github.com/unixpickle/flood$ ls
flood.go
lolphp@pc:~/gocode/src/github.com/unixpickle/flood$ flood.go
flood.go: command not found
lolphp@pc:~/gocode/src/github.com/unixpickle/flood$ go flood.go
go: unknown subcommand "flood.go"
Run 'go help' for usage.
lolphp@pc:~/gocode/src/github.com/unixpickle/flood$ clear

lolphp@pc:~/gocode/src/github.com/unixpickle/flood$ go install
flood.go:10:2: cannot find package "github.com/unixpickle/kahoot-hack/kahoot" in any of:
	/usr/src/pkg/github.com/unixpickle/kahoot-hack/kahoot (from $GOROOT)
	/home/lolphp/gocode/src/github.com/unixpickle/kahoot-hack/kahoot (from $GOPATH)
lolphp@pc:~/gocode/src/github.com/unixpickle/flood$ 

Can you Help me/Or Instruct on how to Setup a Specific GOPATH?

**Comment by unixpickle** [comment]
To setup Go, see https://golang.org/doc/install.

**Comment by mteverst** [comment]
Yeah, you need to use "go run main.go". You'll have to figure out how to setup go first using the link unixpickle posted.
