### ISSUE TITLE
The Exact Command For Running The Flood

### ISSUE THREAD

**Issue by ItsLolPhp** [unixpickle/kahoot-hack#21]
What is the Exact Command For Running The Flood?

> root@pc:~/gocode/src/github.com/unixpickle/kahoot-hack/kahoot-flood# go run main.go
Usage: flood <game pin> <nickname prefix> <count>
exit status 1
root@pc:~/gocode/src/github.com/unixpickle/kahoot-hack/kahoot-flood# chmod +x main.go
root@pc:~/gocode/src/github.com/unixpickle/kahoot-hack/kahoot-flood# flood 451172 floodtest 10
flood: command not found
root@pc:~/gocode/src/github.com/unixpickle/kahoot-hack/kahoot-flood#

**Comment by joondepoon** [comment]
go run main.go <game pin> <username> <amount>
