### ISSUE TITLE
Gopath

### ISSUE THREAD

**Issue by Jayson101** [unixpickle/kahoot-hack#24]
I need some helping creating a Gopath. It is very confusing.

**Comment by mteverst** [comment]
If you read the setup instructions on the "go" website it explains how...

**Comment by Jayson101** [comment]
I have tried.

**Comment by Jayson101** [comment]
They don't make any sense. I have Windows by the way.

**Comment by mteverst** [comment]
I may not be of much help then since I use Linux.

**Comment by Jayson101** [comment]
So who can help me?

**Comment by Jayson101** [comment]
Try sending me the link to the Go website.

**Comment by Jayson101** [comment]
I got a gopath.

**Comment by Jayson101** [comment]
How do I run it now?

**Comment by MatSn0w** [comment]
You can read the [wiki](github.com/unixpickle/kahoot-hack/wiki).
