### ISSUE TITLE
failed to connect: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by tnadzieja** [unixpickle/kahoot-hack#25]
Installed in Ubuntu 14.04, getting this error after installing go1.6 from this tutorial: https://www.digitalocean.com/community/tutorials/how-to-install-go-1-5-3-on-ubuntu-14-04

I've tried reinstalling gorilla's package & this package to no luck. I've had it working before but now it doesn't want to co-operate.

Runs and immediately returns this error: failed to connect: x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: algorithm unimplemented" while trying to verify candidate authority certificate "COMODO RSA Certification Authority")

Thanks in advance.

**Comment by tnadzieja** [comment]
Nevermind, fixed this.

**Comment by unixpickle** [comment]
It might be best if you post what was wrong and how you fixed it here, so that people looking in the future can see it.

**Comment by tnadzieja** [comment]
When I was installing go, I used the apt-get command instead of installing directly from golang.org

Installing from apt-get gave me go version 1.2, extremely outdated and is known to give this error.
So, don't use apt-get when installing the golang. :)
