### ISSUE TITLE
cannot find package

### ISSUE THREAD

**Issue by Wilhelm-af** [unixpickle/kahoot-hack#27]
I have tried so much to fix this but i cant do it. i have tried and tried and now i come here for help.
This is in linux just so you know.

go run Skrivebord/Fritid/kahoot-rand/main.go     ##The command i run

Skrivebord/Fritid/kahoot-rand/main.go:12:2: cannot find package "github.com/unixpickle/kahoot-hack/kahoot" in any of:
    /usr/lib/go/src/github.com/unixpickle/kahoot-hack/kahoot (from $GOROOT)
    ($GOPATH not set)

**Comment by unixpickle** [comment]
This is a problem using Go, and I usually do not try to help with these problems. However, this fix is probably pretty easy, so I'll give it a shot:

```
$ mkdir ~/Go
$ echo "export GOPATH=~/Go" >>~/.bash_profile
$ export GOPATH=~/Go
$ go get github.com/unixpickle/kahoot-hack
$ cd ~/Go/src/github.com/unixpickle/kahoot-hack/kahoot-rand
$ go run main.go
```

If you do not have `git` installed, you will need to install it. If you are on ubuntu, you can use `apt-get` for this.
