### ISSUE TITLE
How To Start Script

### ISSUE THREAD

**Issue by Brakfu** [unixpickle/kahoot-hack#31]
I have been trying to export this script to Google Apps Script but it will not run due to too many errors in the code. Am I using the wrong script runner? Keep in mind I can't run AutoHotKey because I am on a education restricted chromebook. Thank you in advance :)

**Comment by ElliotGluck** [comment]
Just don't even try if you are using a chromebook. Unless you have access to a virtual server then you can't do much. You need a device where you can execute commands.

I would recommend easy server deployment with [Digital Ocean](https://digitalocean.com/). If you are a student which I assume you are, then you can get some free credits through the [Github Student Developer Pack](https://education.github.com/pack).

**Comment by unixpickle** [comment]
You can actually download a statically-linked Go implementation for Chrome OS, as I have done with my Chromebook, but getting everything to work smoothly is very difficult. Regardless, I think this is beyond the scope of this repository, so I am closing the issue.
