### ISSUE TITLE
Creating go path is unclear.

### ISSUE THREAD

**Issue by plasmafart** [unixpickle/kahoot-hack#33]
When trying to make a gopath, nothing that I do works. Its confusing for me. I would like a more simple way on how to make a go path, I cant find it on the "wiki" ethier.
Please just explain here

**Comment by plasmafart** [comment]
I am running Windows 10 not Linux.

**Comment by ElliotGluck** [comment]
http://www.wadewegner.com/2014/12/easy-go-programming-setup-for-windows/
Define in environment variables and run command prompt with admin privileges.

**Comment by unixpickle** [comment]
This is beyond the scope of kahoot-hack. Talk to the Go developers if you have a beef with them, lol.
