### ISSUE TITLE
Bad handshake / Error message?

### ISSUE THREAD

**Issue by TheRedstoneGuy** [unixpickle/kahoot-hack#35]
Every attempt at connection to a kahoot it returns bad handshake, I have tried kahoot-play, kahoot-flood. Same result by all.
![error2](https://cloud.githubusercontent.com/assets/11259035/14715103/3c25d1da-07ad-11e6-8900-503aa7e589f6.png)

Also if i try the command line for kahoot random, it returns this:
![error message](https://cloud.githubusercontent.com/assets/11259035/14714985/c1eb81ee-07ac-11e6-8bd0-ee0616b26a69.png)

Thanks,
~ Colin Masters

**Comment by Arccotangent** [comment]
I don't get this error when I run the scripts.

Make sure you have the latest version, as Kahoot recently changed their protocol.
Other than that, you can try on a proxy and see if it works.

**Comment by TheRedstoneGuy** [comment]
Still getting this for Kahoot random. Seems odd.
![still getting this error](https://cloud.githubusercontent.com/assets/11259035/14731762/96e4e900-0819-11e6-896f-e62838960521.png)

**Comment by unixpickle** [comment]
Have you actually updated the entire codebase? Both the kahoot/ API and all the kahoot tools have been changed.

**Comment by unixpickle** [comment]
I am going to close this now since it has been idle and probably not productive.
