### ISSUE TITLE
No buildable Go source files in src\github.com\unixpickle\kahoot-hack

### ISSUE THREAD

**Issue by KevinLAP** [unixpickle/kahoot-hack#36]
No buildable Go source files in src\github.com\unixpickle\kahoot-hack

I tried to do `go get github.com/unixpickle/kahoot-hack/ ` in cmd, but it returns with that error.
I am running 64 bit Windows 10. I have git installed, and I have already done `go get github.com/gorilla/websocket` to install that dependency.

**Comment by Arccotangent** [comment]
There are no buildable source files in that directory, but in its subdirectories. You have to `git clone https://github.com/unixpickle/kahoot-hack` or just click the Download ZIP button. There are folders with the individual scripts in them inside of the kahoot-hack directory, and you can build and run those Go files.

@unixpickle Maybe the scripts should not be in their own directories.

**Comment by KevinLAP** [comment]
I will try to build them today. I will post back for results.

**Comment by unixpickle** [comment]
If I simply put an empty main.go file in the root repository, it would fix this error. I think it is reasonable to keep the tools isolated in their own sub-directories. The main.go file in the root repository could serve as a doc-comment for godoc.org, anyway.

**Comment by unixpickle** [comment]
Should be fixed by 66f64f7cdf2a2501f585b83258dd845f13cb8ae4.
