### ISSUE TITLE
12:2 non-standard import

### ISSUE THREAD

**Issue by gsmith257** [unixpickle/kahoot-hack#37]
MacBook-Air:~ GrantSmith$ cd /usr/local/go
MacBook-Air:go GrantSmith$ export GOPATH=~/gorilla/
MacBook-Air:go GrantSmith$ cd /usr/local/go/src/github.com/unixpickle/kahoot\ hack/kahoot-rand
MacBook-Air:kahoot-rand GrantSmith$ go run main.go
main.go:17:2: cannot find package "github.com/unixpickle/kahoot-hack/kahoot" in any of:
    /usr/local/go/src/vendor/github.com/unixpickle/kahoot-hack/kahoot (vendor tree)
    /usr/local/go/src/github.com/unixpickle/kahoot-hack/kahoot (from $GOROOT)
    /Users/GrantSmith/gorilla/src/github.com/unixpickle/kahoot-hack/kahoot (from $GOPATH)
MacBook-Air:kahoot-rand GrantSmith$ cd /usr/local/go/src/vendor/github.com/unixpickle/kahoot-hack/kahoot-rand
MacBook-Air:kahoot-rand GrantSmith$ go run main.go
/usr/local/go/src/vendor/github.com/unixpickle/kahoot-hack/kahoot/conn.go:12:2: non-standard import "github.com/gorilla/websocket" in standard package "vendor/github.com/unixpickle/kahoot-hack/kahoot"
## MacBook-Air:kahoot-rand GrantSmith$ 

this is my terminal session and I can't figure out what is going wrong. any help?

**Comment by unixpickle** [comment]
if you actually have a GOPATH setup, you should be able to run the following commands:

```
$ go get github.com/unixpickle/kahoot-hack
$ cd ${GOPATH}/src/github.com/unixpickle/kahoot-hack/kahoot-rand
$ go run main.go
Usage: rand <game pin> <nickname prefix> <count>
       rand <game pin> <name_list.txt>
exit status 1

**Comment by gsmith257** [comment]
I wrote my code as
export GOPATH=~/gorilla/
and i dont know where it is so I cant cd it
