### ISSUE TITLE
New Feature?

### ISSUE THREAD

**Issue by NZHacker** [unixpickle/kahoot-hack#39]
I know that this is the issue section but I am new to Github. Your Kahoot Hack works great but I would like if you could add a feature that makes say 1 or multiple clients search for Kahoot pins to login to. Then it would spit out any working pins that you can then use the hack on. Thanks

**Comment by unixpickle** [comment]
that sounds very evil...I can't think of any good that could come of such a tool. You wouldn't even know who you're messing with.

**Comment by NZHacker** [comment]
oh :(... thanks for the reply though :/

**Comment by NZHacker** [comment]
Im just looking up pins on twitter or live streams currently :D

**Comment by gsmith257** [comment]
@NZHacker You could go on and use a brute force to just run through every possible combination of numbers. Ex: THC-Hydra or Burp suite brute-force.
You would just have to customize it to your own needs.
