### ISSUE TITLE
Websocket not Working

### ISSUE THREAD

**Issue by nmk456** [unixpickle/kahoot-hack#40]
When I run any main.go, I get this error:

`# github.com/gorilla/websocket
../../../gorilla/websocket/client.go:361:32: error: reference to undefined field or method ‘GetCertificate’
   GetCertificate:           cfg.GetCertificate,
                                ^
../../../gorilla/websocket/client.go:370:32: error: reference to undefined field or method ‘ClientSessionCache’
   ClientSessionCache:       cfg.ClientSessionCache,
                                ^
../../../gorilla/websocket/client.go:373:32: error: reference to undefined field or method ‘CurvePreferences’
   CurvePreferences:         cfg.CurvePreferences,
                                ^
../../../gorilla/websocket/client.go:361:3: error: unknown field ‘GetCertificate’ in ‘tls.Config’
   GetCertificate:           cfg.GetCertificate,
   ^`

**Comment by unixpickle** [comment]
what version of Go are you using?

**Comment by nmk456** [comment]
I used `apt-get install`, not sure what version it had.

**Comment by unixpickle** [comment]
You can run `go version` to find out. I remember a time when Go's TLS package that didn't have the `GetCertificate()` API (it was really annoying; it's a useful API). If you are running an out-dated version of Go, you can't expect any new Go code to work.

**Comment by unixpickle** [comment]
Please let me know what version of Go you are running and if upgrading helps. I would like to resolve your problem before closing this issue.

**Comment by zombiestruck** [comment]
Same problem. Version 1.3.3.

**Comment by unixpickle** [comment]
Please update to the latest version of Go and try again.

**Comment by unixpickle** [comment]
For the record, the version of go on `apt-get` is never very up to date. Go 1.3.3 was released in **September, 2014. That is very very old.** You should not expect *any* go software to work on such an old version.

**Comment by amdorj** [comment]
Here's a fix for Debian-based machines (Debian, Ubuntu, etc):
sudo add-apt-repository ppa:ubuntu-lxc/lxd-stable
sudo apt-get update
sudo apt-get install golang

It worked for me; let me know it it works for you.
