### ISSUE TITLE
Ip Adress Ban? How to VPN the hack?

### ISSUE THREAD

**Issue by NZHacker** [unixpickle/kahoot-hack#41]
I have used the hack for a while now and for some reason I cant go on kahoot.it but can go on getkahoot.com and the hack doesn't connect. If I VPN my google chrome I can connect fine but I was wondering if I am ip banned now? How can I VPN my hack?

**Comment by TehRektAngle** [comment]
Try using the desktop version of Betternet. It VPNs everything on your computer.

**Comment by unixpickle** [comment]
This does not directly have to do with the code in this repository, so I am going to close the issue.
