### ISSUE TITLE
Request: Protocol Documentation

### ISSUE THREAD

**Issue by Egoscio** [unixpickle/kahoot-hack#43]
Hello,

Is there any chance you could document the basic kahoot protocol? I'm trying to do similar, but in Node.JS, and I have yet to wrap my head around on the different websocket endpoints.

Cheers,

Egoscio

**Comment by Arccotangent** [comment]
Good idea, I'll get started on protocol documentation very soon.

**Comment by Egoscio** [comment]
How's the documentation going? It's summer, so I guess I'll have to wait until September to actually use it.

**Comment by Arccotangent** [comment]
I've been really busy and haven't made very much progress lately. It's coming along though.

**Comment by Arccotangent** [comment]
Right, Java port is complete and hosted on my GitHub.
I'm making progress with the documentation, and as a note, Websockets aren't required to communicate with Kahoot.

**Comment by Egoscio** [comment]
Excellent! Java is much more readable to me. Also, interesting side note on websockets. I'm not too surprised as they have to provide fallbacks to HTTP longpolling or polling for less advanced schools, etc. but I didn't expect it to be quite easy to access (API wise). Thanks!

**Comment by msemple1111** [comment]
@Egoscio I have a python port of the kahoot hack with a small amount of documentation if you still wanted some.

**Comment by Egoscio** [comment]
@msemple1111 That's pretty cool, Thanks! Protocol/security hasn't changed in the last 9 months, has it?

**Comment by msemple1111** [comment]
@Egoscio When I have re-reverse engineered the protocol, I'll document it properly on my repo.
