### ISSUE TITLE
kahoot-flood and kahoot-rand seem to be patched.

### ISSUE THREAD

**Issue by ElliotGluck** [unixpickle/kahoot-hack#48]

**Comment by msemple1111** [comment]
They both seem to be still broken for me. The actual kahoot protocol has changed so I don't see why it should work.

**Comment by ElliotGluck** [comment]
Back to square one I guess.

**Comment by unixpickle** [comment]
Death with in f77408b894361af231ab0cd01ebbf8928aee5351.
