### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by dylanweb2** [unixpickle/kahoot-hack#5]
"Awaiting Questions" nothing happens after that. we ran through a full game and all it said was awaiting questions.

**Comment by unixpickle** [comment]
It may be that Kahoot changed their internal protocol since I wrote these tools. If anybody wants to try and fix it, be my guest.

**Comment by OG5000** [comment]
how do i use this

**Comment by 19stakev** [comment]
How do I use this?

**Comment by AnUnknownMiner** [comment]
http://lmgtfy.com/?q=how+to+run+go+code

and see README.md

**Comment by OG5000** [comment]
i still dotn undersatand


On Fri, Oct 16, 2015 at 12:52 PM, Spencer Sederberg <
notifications@github.com> wrote:

> http://lmgtfy.com/?q=how+to+run+go+code
>
> and see README.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/unixpickle/kahoot-hack/issues/5#issuecomment-148767309>
> .
>



-- 
*I LIKE CHEESE*

**Comment by dorkrepublic** [comment]
unixpickle, may I ask what tool you used for the dumps? I am planning on remaking this tool.

**Comment by unixpickle** [comment]
@dorkrepublic I used Chrome. It's developer console lets you dump Websocket traffic.

**Comment by unixpickle** [comment]
After the rewrite that I did today, I tested everything and it works as well as I'd expect.

Given this, I am going to close this issue. If the issue persists, please open a new issue and specify which tool is having the problem.
