### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by therealkeeg1** [unixpickle/kahoot-hack#50]
I think kahoot has changed their protocol again. The bots do not join the given game pin.

**Comment by Nexaller** [comment]
Yes, whenever I try to run it, it gives me the "websocket: bad handshake" error.

**Comment by i695077** [comment]
Same here.

**Comment by msemple1111** [comment]
Kahoot added a simple maths challenge for the computer to calculate.

**Comment by unixpickle** [comment]
Dealt with in f77408b894361af231ab0cd01ebbf8928aee5351.
