### ISSUE TITLE
[REQUEST] - Update Kahoot! hack

### ISSUE THREAD

**Issue by i695077** [unixpickle/kahoot-hack#51]
Is anyone able to update the Kahoot! hack? Seems like they have changed the protocol, as we get same error, anyhow what we do: "websocket: bad handshake".

**Comment by msemple1111** [comment]
They have updated the protocol again, this time including a challenge to stop bots. It is only some maths so that should be easy to implement.

**Comment by unixpickle** [comment]
Just updated the code for the new challenge and it looks like kahoot-play and kahoot-flood work.
