### ISSUE TITLE
Websocket not connecting: Bad handshake

### ISSUE THREAD

**Issue by aleder1** [unixpickle/kahoot-hack#55]
When I try to connect I get the error: failed to connect: websocket: bad handshake
I am on the latest version of go programming language 
Please help

**Comment by unixpickle** [comment]
I have been modifying this code a lot to keep it up to date with Kahoot's latest challenges. Do you have the latest version of the code (updated today)?

**Comment by unixpickle** [comment]
By the way, this serves as an example of why you should always use `go get` to install Go packages rather than manually downloading things in some nonstandard fashion. If you used `go get`, all you have to do to update the package is `go get -u github.com/unixpickle/kahoot-hack/kahoot`.

**Comment by danhab99** [comment]
What is all this, I never even tried to use this package yet

**Comment by unixpickle** [comment]
@danhab99 not sure what you are referring to by "all this". This package is for performing playful "hacks" on a quiz/survey website. Recently, said website has been trying to crack down on "security" to prevent programs like this from working, so this package requires a bit of regular maintenance.
