### ISSUE TITLE
Unsupported challenge

### ISSUE THREAD

**Issue by EcMiner** [unixpickle/kahoot-hack#56]
Everytime I try to run **any** of the hacks, i.e. flood or rand, it says unsupported challenge, like in the image below:

![unsupported challenge error](http://image.prntscr.com/image/aa2a0e762c9540f9855902b4cdf89321.png)

I'm on Windows 10, using golang version: `go1.7.3 windows/amd64`

**Comment by unixpickle** [comment]
Make sure you are running the latest version. The latest code, updated today, will hopefully keep working for a while. In general, make sure you are using the latest version before filing an issue.

**Comment by unixpickle** [comment]
In fact, I know this was not on the latest version, because the latest version cannot produce that error.
