### ISSUE TITLE
No go file listed

### ISSUE THREAD

**Issue by EagleRaptor** [unixpickle/kahoot-hack#57]
I'm trying to use the Rand tool but i get the "no go file listed" error when i'm obviously writing "go run D:\GO path\src\github.com\gorilla\kahoot-hack-master\kahoot-rand\main.go" which directs to "main.go" so it should work right? but its not working for some reason. Please help.

**Comment by unixpickle** [comment]
That file path has a space in it. I'd expect you'd need to surround it in quotes. Otherwise, the first part before the space is treated like a path.

**Comment by EagleRaptor** [comment]
so: go run "D:\GO path\src\github.com\gorilla\kahoot-hack-master\kahoot-rand\main.go"
? if not i dont get what you mean.

**Comment by unixpickle** [comment]
That is what I mean

**Comment by EagleRaptor** [comment]
alright ill try that

**Comment by EagleRaptor** [comment]
worked now. thanks.
