### ISSUE TITLE
bad handshake

### ISSUE THREAD

**Issue by LordBunny** [unixpickle/kahoot-hack#58]
I can't flood this is the error
![can t](https://cloud.githubusercontent.com/assets/20775355/20454884/f9d38ee8-ae4c-11e6-9fe0-80eeaf08a71e.PNG)

**Comment by LordBunny** [comment]
Fixed it https://github.com/LordBunny/Kahoot-Flood/

**Comment by unixpickle** [comment]
Yeah, as you can tell I had to update this recently to work with some of the changes kahoot has made.
