### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by Danielix99** [unixpickle/kahoot-hack#59]
Hi i've recently downloaded kahoot and after it, i've set it up, i tried to run it, it worked pretty well, but after a while, i've reused it and it give me this error:

`ROOT:~/gg/src/github.com/unixpickle/kahoot-hack/kahoot-flood> go run main.go 1291712 BOT 10
failed to connect: failed to create session: Get https://kahoot.it/reserve/session/1291712: dial tcp 54.220.65.78:443: i/o timeout
exit status 1
`

**Comment by unixpickle** [comment]
You must upgrade to the latest version of the code. Kahoot has changed things around, so the old code does not work.

**Comment by Danielix99** [comment]
ok i will try now

**Comment by Danielix99** [comment]
it continue to tell me that:

`ROOT:~/gg/src/github.com/unixpickle/kahoot-hack/kahoot-flood> go run main.go 1291712 bot 10
failed to connect: failed to create session: Get https://kahoot.it/reserve/session/1291712: dial tcp 54.220.65.78:443: i/o timeout
exit status 1
`

**Comment by Danielix99** [comment]
i dont know the GO language but if there is an explaination of what you did in your code i can try to do some port

**Comment by unixpickle** [comment]
Hmm, after you run the program, does

**Comment by Danielix99** [comment]
Sorry i'm a student, now i'm at home, i will try the code over my pc to check if kahoot block ip, it can be possible but i told kahoot only to join 10bot, anyway i will try soon

**Comment by Danielix99** [comment]
Ok I've checked, running it on my pc result in to a working script, then i suppose that my server have problem with kahoot, closr it
