### ISSUE TITLE
failed to defeat challenge

### ISSUE THREAD

**Issue by drsirmrpresidentfathercharles** [unixpickle/kahoot-hack#60]
Upon connecting to a game , I get an error that states:

`failed to connect: failed to create session: failed to defeat challenge: (8662 + 1) * (6334 * 3561)`

Does kahoot now have a sort of "captcha"?

**Comment by unixpickle** [comment]
They did add an internal "captcha", but my program should be able to defeat it. I just tested it and it worked. Make sure you are running the latest version of the code.

**Comment by drsirmrpresidentfathercharles** [comment]
I was using the latest version of the code, however, the domain that the code was using for eval was blocked by my institution's filter. A quick proxy configuration fixed that.

**Comment by unixpickle** [comment]
Oh, glad it's fixed. Do you think using HTTPS on the domain would also have fixed it? I've been considering forcing HTTPS, but not without a reason.

**Comment by drsirmrpresidentfathercharles** [comment]
No. My institution just hates websites like that. Is there any Go package that does JS or Math evaluation like that?

**Comment by unixpickle** [comment]
Math evaluation, yes; JavaScript evaluation, no. For now, Kahoot's challenges can be solved with an expression parser (e.g. [this one](https://github.com/Knetic/govaluate)). In the future, however, they may add JavaScript-specific challenges to break other people's code. Without a tool like Node.js, which is what safeval.pw uses, evaluating JavaScript is very difficult (and building V8 or some other JS engine as a dependency of kahoot-hack would be extremely complicated). Just as a concrete example, Kahoot could make a challenge like `(true+false)*(1-[])+100`.

It might be worth trying an expression-parser first before using safeval.pw as a fallback. The reason I haven't added an expression parser up until now is simple: if I added another dependency to this repository, I would immediately receive dozens of pull requests from script kiddies complaining that an error message comes up about a missing dependency.
