### ISSUE TITLE
could not defeat session challenge

### ISSUE THREAD

**Issue by lopy67** [unixpickle/kahoot-hack#62]
whne trying to run go run /usr/local/go/src/github.com/unixpickle/kahoot-hack/kahoot-flood/main.go 8674225 fugitiv 40
```
go run /usr/local/go/src/github.com/unixpickle/kahoot-hack/kahoot-flood/main.go 8674225 fugitiv 40
failed to connect: failed to create session: could not defeat session challenge
exit status 1
```

Any ideas?

**Comment by unixpickle** [comment]
Update to the latest version of the code. I know you are not using the latest version, because the most recent version cannot produce an error with the message "could not defeat session challenge".
