### ISSUE TITLE
Failed to defeat challenge.

### ISSUE THREAD

**Issue by TeamMedusa** [unixpickle/kahoot-hack#63]
Hello.
I'm getting this issue when trying to enter with 50 random bots (Or more).

User:kahoot-rand User$ go run main.go 283386 NAME 50
failed to connect: failed to create session: failed to defeat challenge: decode('f5PkMP2ObTFq88EYZ6GG3uiYWwVKA2MD0bKOc10MTdEKIEqUUtKiO9rkeSCllTofwjr95lF6gXfb5zehKp2O1sl0OcIj0WK9lzp2'); function decode(message) {return _.replace(message, /./g, function(char, position) {return String.fromCharCode((((char.charCodeAt(0) * position) + 1) % 77) + 48)});}
exit status 1

Any idea why?

**Comment by unixpickle** [comment]
Make sure [http://safeval.pw](http://safeval.pw) loads for you. This depends on safeval for connecting to kahoot's system.
