### ISSUE TITLE
Unsupported challenge

### ISSUE THREAD

**Issue by reesercollins** [unixpickle/kahoot-hack#66]
Here is my log:

failed to connect: failed to create session: unsupported challenge: decode('4KKhWL8g8lkI5gtpjL7cUmay8jCHidMKNsmF2xQgRL7TpKh07xAEqZJ8TlNy6bME8lvqmogknRsVIa6RppN3SYXg1XbReRINkH0c'); function decode(message) {var offset = ((69 * 87) + (89 * 96 * 39 + 97) * 62); console.log("Offset derived as:", offset); return _.replace(message, /./g, function(char, position) {return String.fromCharCode((((char.charCodeAt(0) * position) + offset) % 77) + 48);});}
exit status 1

**Comment by unixpickle** [comment]
It currently works fine--I just ran it and succeeded.

When did this happen? I had to add something to safeval.pw this morning to fix a bug which Kahoot introduced with their latest "challenge". That update was around 11AM EST this morning (about 3 hours ago). If you tried before then, I'd expect it to have failed.

**Comment by LordBunny** [comment]
@unixpickle Could you join my discord? I made a way to make flood more easy. And I flood for people using a discord bot

**Comment by unixpickle** [comment]
@LordBunny if you use this tool or a related tool to flood kahoot, then your "discord" (whatever that is) depends on safeval.pw. Thus, a bug in safeval is a bug in your system.

**Comment by reesercollins** [comment]
Safeval.pw?

**Comment by unixpickle** [comment]
safeval.pw is the website that kahoot-hack uses internally to connect to Kahoot.

**Comment by reesercollins** [comment]
It's being blocked by my firewall for web-advertisements

**Comment by unixpickle** [comment]
Then there is no way to run kahoot-hack besides using a server to run the hack or having someone else do it.

**Comment by unixpickle** [comment]
In an attempt to fix the firewall issue, I have a question:

When you attempt to load the website with https (go to [https://safeval.pw](https://safeval.pw)), does it work then? I remember some firewalls a few years ago not being able to deal with https domains; I don't know if that is still the case.
