### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by k375725** [unixpickle/kahoot-hack#69]
Hello!

I want to try to start the flood using CMD on PC using this code: C:\> go run /usr/local/go/src/github.com/unixpickle/kahoot-hack/kahoot-rand/main.go 1456785 nickname 200

Then I get this error message: GetFileAttributesEx /usr/local/go/src/github.com/unixpickle/kahoot-hack/kahoot-rand/main.go: The system cannot find the path specified.

Do I use wrong code? Or do I need to install or setup something first?

Thanks in advance!

**Comment by bjorn3** [comment]
Does `file /usr/local/go/src/github.com/unixpickle/kahoot-hack/kahoot-rand/main.go` give a error?

**Comment by k375725** [comment]
C:\>file /usr/local/go/src/github.com/unixpickle/kahoot-hack/kahoot-rand/main.go
'file' is not recognized as an internal or external command,
operable program or batch file.

**Comment by k375725** [comment]
I made it!

C:> go run go/src/github.com/unixpickle/kahoot-hack/kahoot-rand/main.go 6454562 user 20

But this enters bots much slower than if I open the program and do it there...

**Comment by k375725** [comment]
Do you know how to make it enter bots faster? When using the exe file, it works rapidly, but when using CMD they will be entered one by one very slow...

**Comment by unixpickle** [comment]
There should not be a difference in speed no matter how you run the program, as long as the exe and the source code are from the same version of kahoot-hack.

**Comment by k375725** [comment]
I see a big difference, even though everything is at is should. Also, my antivirus says that the exe files are trojans. Is that so?

**Comment by unixpickle** [comment]
I do not provide any EXE files. If you have downloaded them from somewhere, that is a third party with whom I am not associated.

**Comment by Imanton1** [comment]
I believe k375725 is referring to your .go files sent through "go -build" to create EXE files.
But no, they are not 'trojans', as you can see by reading the source.

**Comment by k375725** [comment]
I downloaded from the YouTube video below. So that is not what I should?

https://www.youtube.com/watch?v=gYDOu2ORUFs

https://mega.nz/#!okJykCIR

**Comment by k375725** [comment]
"I believe k375725 is referring to your .go files sent through "go -build" to create EXE files.
But no, they are not 'trojans', as you can see by reading the source."

How do I do this?

> "I believe k375725 is referring to your .go files sent through "go -build" to create EXE files.
But no, they are not 'trojans', as you can see by reading the source."

How do I do this?

**Comment by bjorn3** [comment]
go build go/src/github.com/unixpickle/kahoot-hack/kahoot-rand/main.go

**Comment by k375725** [comment]
Where does this exe file appear?

**Comment by bjorn3** [comment]
current dir if i am correct

**Comment by k375725** [comment]
Nope, nothing there...

**Comment by bjorn3** [comment]
```
cd go/src/github.com/unixpickle/kahoot-hack/kahoot-rand/
go build main.go
```

**Comment by k375725** [comment]
That worked! What do I use the "main" exe file to then?

**Comment by unixpickle** [comment]
@k375725 those youtube videos you linked to are not associated with me in any way. I cannot endorse them. For all I know, the executables *are* viruses.

**Comment by k375725** [comment]
Ok, thanks for that, then I will not use them anymore.

What can I use "main.exe" to?
