### ISSUE TITLE
HELP!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by k375725** [unixpickle/kahoot-hack#72]
I use this command in CMD on PC:

go run go/src/github.com/unixpickle/kahoot-hack/kahoot-rand/main.go 1234567 usernames 50

But I get this error message:

'go' is not recognized as an internal or external command,
operable program or batch file.

I am running it from C:\ and GO is placed there. What can I do to solve this?

**Comment by Imanton1** [comment]
see if this helps: http://stackoverflow.com/questions/23722405/go-is-not-an-internal-or-external-command

**Comment by k375725** [comment]
No, it doesn't work...

**Comment by goerick** [comment]
You need to install go

**Comment by Imanton1** [comment]
can you run "C:\Go\bin\go.exe"?

**Comment by k375725** [comment]
It worked perfectly when I had GO installed. But I tried to uninstall it but still keep the GO files, so that I could remove the program from the list of installed programs. Then it did not work.

So I must have GO installed?

**Comment by bjorn3** [comment]
It must be in your %PATH%

**Comment by k375725** [comment]
What? How to do that? Sorry, I am completely noob.

**Comment by bjorn3** [comment]
set PATH="C:/go/bin;%PATH%"

**Comment by k375725** [comment]
How do I do that? Do I use CMD? The GO guides are so difficult...

**Comment by bjorn3** [comment]
run it in every cmd window before you try to run go.

**Comment by k375725** [comment]
Do I just write this in CMD?

set PATH="C:/go/bin;%PATH%"

**Comment by bjorn3** [comment]
yes

**Comment by k375725** [comment]
Ok, tested and nothing happened yet. Will try to uninstall GO and try then. Thanks!

**Comment by bjorn3** [comment]
i think it is a missunderstanding. to clarify: run `set PATH="C:/go/bin;%PATH%"` first then `go run go/src/github.com/unixpickle/kahoot-hack/kahoot-rand/main.go 1234567 usernames 50`
