### ISSUE TITLE
Failed to create session:

### ISSUE THREAD

**Issue by MrWouterNL** [unixpickle/kahoot-hack#74]
This is my error:
go run main.go 256172 hi 10

failed to connect: failed to create session: failed to defeat challenge: decode('UYHksVGbxUn34DeTHiXMiWH44Mmg7mc3bt1zvf48yp64wgVUUgerzM1hJTJOEVGRzlPbPtKNxIfO8Ip6K9fN36Sw6LPPQtZHbVZs'); function decode(message) {var offset = (67 + ((100 + 19) * 22 * (74 * 38))); console.log("Offset derived as:", offset); return _.replace(message, /./g, function(char, position) {return String.fromCharCode((((char.charCodeAt(0) * position) + offset) % 77) + 48);});}

exit status 1

**Comment by MrWouterNL** [comment]
I am running kahoot flood

**Comment by unixpickle** [comment]
Try again with the newest version of the code.
