### ISSUE TITLE
kahoot-xxs not working

### ISSUE THREAD

**Issue by Jaspenton** [unixpickle/kahoot-hack#81]
i am either not doing it correctly or its not working can u please fix it or help me do it correctly

**Comment by Imanton1** [comment]
can you explain what you are doing to try and run it?

**Comment by unixpickle** [comment]
a) I believe you mean xss not xxs
b) in the README i explicitly state that Kahoot fixed the XSS since it was a security hole.

**Comment by Imanton1** [comment]
that was fast... Could you make it work again if you tried harder? XSS gets hilarious somtimes.

**Comment by Jaspenton** [comment]
so then why do u keep the option there?

**Comment by unixpickle** [comment]
It's not an "option", it's a file. The README's name implies that you should read it. If you read it, you'd know that kahoot-xss was *not* an option.
