### ISSUE TITLE
I get an error

### ISSUE THREAD

**Issue by illuminati945** [unixpickle/kahoot-hack#82]
goroutine 8 [running]:
panic(0x232480, 0xc420012080)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1

**Comment by unixpickle** [comment]
That is not the full error message. You selected a tiny snippet of the error message. In fact, the snippet you selected is the least useful part.

**Comment by illuminati945** [comment]
The issue was that i couldn't connect to safeval.pw because of my schools filter. Unless you can help me get passed that theres not much we can do

**Comment by unixpickle** [comment]
Ah ok. I am going to close this issue then.

**Comment by unixpickle** [comment]
The current version no longer requires safeval.pw (for now).
