### ISSUE TITLE
Failed to create session; i/o timeout?

### ISSUE THREAD

**Issue by moofy** [unixpickle/kahoot-hack#85]
Possible duplicate of #59.

I've tried running the `kahoot-flood` script on my local Windows 10 machine and I have no issues at all. However it's more practical for me to run it on my server, but I get the following error when trying to do so:

```bash
failed to connect: failed to create session: Get https://kahoot.it/reserve/session/8295943: dial tcp 54.91.242.100:443: i/o timeout
exit status 1
```

**Server**
Debain 8.7/x64
go-lang 1.8/amd64

gorilla/websocket **is** installed with the following command: `go get github.com/gorilla/websocket`
Along with that the path to the script on the machine is located here:

```bash
$HOME/go/src/github.com/unixpickle/kahoot-hack/kahoot-flood/main.go
```

Ideas?

**Comment by unixpickle** [comment]
Is the server on the same network as your windows computer? Perhaps kahoot started blocking a large IP block used by EC2 or something.

**Comment by moofy** [comment]
Yes it's running on the same network, I just tested on a different network and I get the same error unfortunately.

**Comment by moofy** [comment]
Closing due to no response from the developer.
