### ISSUE TITLE
If game pin is 7 numbers, none of these will work

### ISSUE THREAD

**Issue by Tudwad** [unixpickle/kahoot-hack#86]
If you have a 6 pin game code it's fine, but now kahoot has 7 pin codes which don't work with any of these scripts.

Please fix lol

**Comment by Imanton1** [comment]
I have had in the past both length six and seven game codes, can you elaborate further what the problem you are having is? Does it give an error?

**Comment by unixpickle** [comment]
There's no theoretical reason it shouldn't work for 7-digit game pins. In fact, I and others have successfully used these tools with such pins. Could you please share the specific nature of the error you encounter?

**Comment by unixpickle** [comment]
This isn't a real problem.
