### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by thomas2206** [unixpickle/kahoot-hack#88]
i went in to CMD and wrote this ```go get github.com/gorilla/websocket```
but i got an error message: go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/gorilla/websocket: exec: "git": executable file not found in %PATH%

what did i do wrong?

**Comment by thomas2206** [comment]
i am running this version on windows 10 64bit go version go1.8 windows/amd64

**Comment by bjorn3** [comment]
You need to install git.
