### ISSUE TITLE
Android Installation?

### ISSUE THREAD

**Issue by JarrettFritz** [unixpickle/kahoot-hack#89]
How does this installation work? I ran it with the Readme but I'm stuck. Any help?

**Comment by Noxturnix** [comment]
Hi JarrettFritz,

Can you show me what's the system saying when you got stuck?

**Comment by JarrettFritz** [comment]
It's more to run it I guess. It says to type exit. Don't know what to do next

**Comment by Noxturnix** [comment]
Ok, now you have installed kahoot-hack on your device. You need to restart the by typing `exit` and open the app again. The way to use the hack is typing `go run kahoot/[hack-name.go]`.

Example:

    go run kahoot/flood.go

And the system will show you about the usage message:

    Usage: flood <game pin> <nickname prefix> <count>
           flood <game pin> <name_list.txt>

In this case I will show you how to use flood.go:

    go run kahoot/flood.go 537837 Bot 20

The number `537837` is the game pin. The text `Bot` is the nickname prefix. And the number `20` is the amout of bots.

**Comment by JarrettFritz** [comment]
Thank you!
