### ISSUE TITLE
site/main.go not opening

### ISSUE THREAD

**Issue by lesleyxyz** [unixpickle/kahoot-hack#90]
Everything works fine except the site directory:

If I do 'go run main.go' it gives the correct help menu:

`Usage: site <port>`

and if I then do:
go run main.go 81
it doesn't do anything
nor does it do anything if I use an invalid port (go run main.go 10000 or -1)

**Comment by unixpickle** [comment]
The command produces no output. It serves an HTTP server on the given port. Also, 10000 is a valid port number.
<img width="423" alt="screen shot 2017-03-18 at 5 16 43 pm" src="https://cloud.githubusercontent.com/assets/406021/24076053/b0289ecc-0bfe-11e7-9732-dd5999d107e9.png">

**Comment by unixpickle** [comment]
To clarify, is it that the command simply exits right away, or that you run it and its sits there waiting doing nothing? I notice that the code doesn't report errors for listening on the port, so there may be a silent error that is not being reported.

**Comment by WillDott** [comment]
Yeah also having the same issue, ran the webserver and just sat there doing nothing.

Screenshot provided:
http://imgur.com/a/t1PA3

**Comment by unixpickle** [comment]
@WillDott to be clear, just because a program doesn't print any output doesn't mean it's not doing something. After you run that command, you need to go to a browser and navigate to `http://localhost:1123`.

**Comment by WillDott** [comment]
Yes sorry my poor explanation have tried that and 127.0.0.1:1123 only to return a 404

**Comment by unixpickle** [comment]
Will re-open if you provide more information about your system and an actual screenshot of the "404" you see...
