### ISSUE TITLE
dial tcp i/o timeout exit status 1

### ISSUE THREAD

**Issue by john1234brown23** [unixpickle/kahoot-hack#91]
Alright i have personally tried to ping kahoot.it but it isnt working im thinking maybe its my side im using Codeanywhere Virtual machine atm its linux ubuntu and this is the error code i always get when i try to do any of the kahoot-hack's

`cabox@box-codeanywhere:~/workspace$ go run kahoot-hack/kahoot-rand/main.go 3298681 Dingus_ 100                                                 
Entered with 100 bots.                                                                                                                         
Terminate this program to stop the automatons...                                                                                               
failed to connect: failed to create session: Get https://kahoot.it/reserve/session/3298681: dial tcp 54.167.27.3:443: i/o timeout              
exit status 1                   `
^ that is the console im thinking it might be my ip is blocked like the machines ip is blocked but at the same time ive noticed other people are having a similar error.

**Comment by acz13** [comment]
Can confirm

**Comment by GNUGradyn** [comment]
If you cannot ping kahoot.it, the problem is on your side.

**Comment by acz13** [comment]
Think it might be kahoot blocking certain IPs, he was using a cloud IDE service so...

**Comment by jclgc** [comment]
I have the same problem, pinging kahoot.it gives me 100% package loss and every device connected to my wifi that tries to open kahoot.it keeps loading infinitely

**Comment by acz13** [comment]
Kahoot is probably detecting spammers

**Comment by jclgc** [comment]
Is there anyway to bypass it?

**Comment by unixpickle** [comment]
It's weird that they are blocking IPs, considering that Kahoot is typically used in schools where all the students will be on the same IP.

**Comment by acz13** [comment]
@unixpickle yeah, but I can't think of another possibility (on one cloud VM I tried flooding a game, that worked, but when I tried again I got this error
)

**Comment by unixpickle** [comment]
The way around this would be: simply run the hack from your actual computer connected to the same internet connection as everyone else.

**Comment by john1234brown** [comment]
Alright so if im lucky and my school is so unknown i could use one of the school computers and spam kahoot and then get our entire school blocked maybe.

**Comment by acz13** [comment]
if you can get go on it or a compiled exec yeah maybe
