### ISSUE TITLE
main.go:13:2: cannot find package "github.com/unixpickle/kahoot-hack/kahoot" in any of:

### ISSUE THREAD

**Issue by samvdkris** [unixpickle/kahoot-hack#93]
main.go:13:2: cannot find package "github.com/unixpickle/kahoot-hack/kahoot" in any of:
        C:\Go\src\github.com\unixpickle\kahoot-hack\kahoot (from $GOROOT)
        C:\Users\sam\go\src\github.com\unixpickle\kahoot-hack\kahoot (from $GOPATH)

**Comment by unixpickle** [comment]
You need to install Go properly and download the package into your GOPATH correctly.
