### ISSUE TITLE
Can't pass parameters!

### ISSUE THREAD

**Issue by met4lface** [unixpickle/kahoot-hack#95]
This is less an issue and more my lack of knowledge of Go. When I try to run main.go (like this: "go run kahoot-flood\main.go"), the terminal returns: 

Usage: flood < game pin > < nickname prefix > < count >

How do I pass this information to Go? (Note: I am running Windows, problem number 1).

**Comment by unixpickle** [comment]
The full message it prints out should be

```
Usage: flood <game pin> <nickname prefix> <count>
```

In that example, `flood` just stands for the command you used to run the program (in this case `go run kahoot-flood\main.go`). You have to have a game pin, a nickname prefix (e.g. "hi"), and a count (the number of bots). For example:

```
go run kahoot-flood\main.go 123456 hi 10
```
