### ISSUE TITLE
Overview of Code

### ISSUE THREAD

**Issue by jeffx99** [unixpickle/kahoot-hack#97]
I'm trying to write my own flood hack in C++ and I'm wondering how you did this. I have a rough idea of how to go about this (copy-pasted from a previous request I made):

1. Send GET to kahoot for kahoot.it/reserve/session/[PIN]/?[Current Time?????]
2. Do some weird stuff with twoFactorAuth and "challenges." 
3. Make a POST request with my name and stuff.

I've gotten this from analyzing the requests sent through Chrome's Developer Tools Network Tab. I don't know what is happening in step two however.

~~For step 2 I do understand now that the JS code is evaluated and the XOR is taken with the session token. (whyyyyy?)~~ Makes some sense now, thats just how kahoot decided to do their CRAM.

Looking into CometD, it seems the information needed should be in the Docs to make a POST for step 3, hopefully. Makes much more sense.

EDIT: How do you know what data to send through using CometD? Is there some way I can anaylze the traffic sent? Chrome only gives me a POST request made out to api.amplitude.com

**Comment by bjorn3** [comment]
> For step 2 I do understand now that the JS code is evaluated and the XOR is taken with the session token. (whyyyyy?)
Trying to prevent hacks like this I guess

**Comment by jeffx99** [comment]
Well then how would anyone figure out that you had to do an XOR with the session token?

**Comment by bjorn3** [comment]
> Is there some way I can anaylze the traffic sent?

You can use something like http://www.telerik.com/fiddler

**Comment by unixpickle** [comment]
Chrome dev tools let's​ you do everything you need. It has a feature to view WebSocket traffic, which is what cometd uses by default.

For the challenge used to authenticate, I had to look through their JS code a bit. The code in this repository should hopefully be enough to prevent you from having to do that.

**Comment by unixpickle** [comment]
I'm going to close this issue for now since it's not an actual problem.
