### ISSUE TITLE
Two Factor Bypass not working

### ISSUE THREAD

**Issue by mudzkipz** [unixpickle/kahoot-hack#98]
Seems like the two factor bypassing is not working for me?
I can run the program fine on a kahoot with no two-factor, but when I try it on one with two-factor enabled, it doesn't work. There is no error message, cmd looks like normal, but simply no bots show up. 

Spent ages puzzling over this, tried looking at the code and noticed the eval.go and other scripts in the '\kahoot-hack\kahoot\' folder didn't seem to ever be used, (forgive me if I'm wrong though, I don't really know what I'm talking about.)

Would be great if I could have this working by tomorrow, any help or suggestions are appreciated.

**Comment by unixpickle** [comment]
2FA is currently not supported.
