### ISSUE TITLE
Feature Request (Correct Answer)

### ISSUE THREAD

**Issue by end360** [unixpickle/kahoot-hack#99]
# What I Desire
The feature would be a bot to answer correctly. I've almost managed to do it myself in javascript but kahoot doesn't seem to like it when you inject an answer into their code (I get kicked with no message on screen). There are some things I'm missing as well. Basically all you do is figure out what game it is on the kahoot site you use to actually start a game, and show all the answers.

# How it works
1. It figures out what the game is on create.kahoot.it (the site where you start a game). I haven't found out how to do this automatically yet, since my tools are limited at school.
2. It loads the page for that game and clicks the "Show all Answers button" (Probably able to be skipped with a bot)
3. Searches for all divs with a class of "answer-label__correct-icon"
4. Gets all their parents
5. Determines what button it is by parent class "answer-label--0" is red, "answer-label--1" is blue "answer-label--2" is yellow and "answer-label--3" is green
6. Relays answers to client
7. Profit

# Roadblocks
* I can't seem to find how to get the url ID for the game (Not the game pin)
* I'm not experienced with Go so I wouldn't be able to help on that.
* In JS kahoot has a form of anticheat that kicks you out if you get the angular scope and run selectAnswer with the correct answer

**Comment by end360** [comment]
Step 2 could be skipped because the buttons are hidden with the hidden tag, not removed.

**Comment by reteps** [comment]
Can you show us what you've made? The results on `create.kahoot.it` are javascript based, so I don't think we would be able to use a crawler and get the page results.

**Comment by reteps** [comment]
I could make a golang `helper`, that gives the answer to every question.

**Comment by unixpickle** [comment]
I'm not convinced that this is possible. If you aren't logged into create.kahoot.it as the user who made the quiz, and if the quiz is not marked as "public", then I don't know of any way to see the quiz or its answers.

**Comment by reteps** [comment]
but for public quizzes, you can search quizzes and find the correct one. Off of this you could (theoretically) gain the answer to each question using some serious page regex / something else.

**Comment by aleder1** [comment]
Could you share what you have at the moment?

**Comment by reteps** [comment]
I haven't been working on it. I want to see what @end360 has done, so I can build off of it.

**Comment by end360** [comment]
Oh, I honestly forgot all about this. I no longer have my code because I forgot it, along with many other things on my school account and I just graduated. I could make it again but it was really just a test. I had two important functions. One would serialize the answers by looping through all HTML elements that had the checkbox, and the other would deserialize it and call the answer function in js (which would then cause your game to go to a white screen and stay there). It wasn't the best because I had to manually serialize it, but I planned on making it into more until the white screen thing happened and I graduated.

**Comment by end360** [comment]
Well, it looks like I did try sending them to myself but Gmail blocked them because of the .js attachment :(

**Comment by end360** [comment]
After some searching through my Google account, I found out that I sent myself the js through email, although I believe it may be an older version so it may not work, looking into it now.

**Comment by reteps** [comment]
I don't understand how you just need the url - is this a quiz that is currently running?

**Comment by reteps** [comment]
Made it. Works beautifully. [this is it](https://github.com/reteps/kbot). Please give a star!!!

**Comment by reteps** [comment]
See #107 for PR. [CLOSE THIS]
